[14.0] [MIG]  fieldservice_available_worker: Migration to 14.0
Escodoo/fieldservice-addons pull request #8
Opened 2023-11-08 13:32 UTC by Alisson-Jns

cc @marcelsavegnago  @Escodoo/desenvolvedores

2023-11-10 16:43 UTC, kaynnan requested changes
Tratar também: 2023-11-10 16:26:30,366 26 WARNING devel odoo.modules.loading: The model fsm.available.worker has no access rules, consider adding one. E.g. access_fsm_available_worker,access_fsm_available_worker,model_fsm_available_worker,base.group_user,1,0,0,0

Referente ao base.group_user não vale a pena ser ele, coloca o mesmo grupo que tem no fieldservice_skill referente a dispacher e com permissões 1.1.1.1

2023-11-10 16:43 UTC, kaynnan commented on fieldservice_available_worker/wizards/fsm_available_worker.py
> +
Tratar o warning : 2023-11-10 16:26:29,850 26 WARNING devel odoo.models: The model fsm.available.worker has no _description

2023-11-10 16:43 UTC, kaynnan commented on fieldservice_available_worker/wizards/fsm_available_worker.py
> +    territory_id = fields.Many2one("fsm.territory", string="Territory")
Tratar o warning: 2023-11-10 16:26:29,872 26 WARNING devel odoo.fields: Field fsm.available.worker.territory_id with unknown comodel_name 'fsm.territory'

O fsm.territory pode ter sido renomeado, da uma comparada entra as versões 12 e 14. Por meio do histórico de commit vc consegue ter uma base do que foi alterado/excluido/adicionado.

Aqui na v12 de como era: https://github.com/OCA/field-service/blob/12.0/fieldservice/models/fsm_location.py#L27

Muda para a 14 e compara sobre o model `fsm_location` referente ao módulo fieldservice como está nomeado o `fsm.territory`

2023-11-21 13:46 UTC, marcelsavegnago commented
@Alisson-Jns chegou a tratar os comentários do @kaynnan  ?

2023-11-22 22:53 UTC, kaynnan approved these changes
REVIEW [FUNCTIONAL AND CODE] APPROVED

Action: Available Workers

![image](https://github.com/Escodoo/fieldservice-addons/assets/53870822/384b31c6-5886-45fd-b426-a40a9401718b)

2023-11-24 14:00 UTC, merged